### ISSUE TITLE
Sketch out git tag based build process

### ISSUE THREAD

**Issue by joshuacoles** [Better-Conversations/ruby-flightplans#3]
- Checkout revision
- Load auto-build extension on the flight plan class to allow for discovery / building
- require relative the path provided
- Build should go to a standard place to be plucked out

**Comment by joshuacoles** [comment]
```shell
bundle exec bcf-fp-generate <root_dir> <relative_flightplan_path>
```
Will output the JSON to stdout. Questions remaining for the build itself are discovery.

**Comment by simoncoles** [comment]
Remember this is a public repository so any secrets used to submit to the coordinator need to be here https://github.com/Better-Conversations/ruby-flightplans/settings/secrets/actions
